### ISSUE TITLE
[Feature] Custom window bar

### ISSUE THREAD

**Issue by zabbix-byte** [zabbix-byte/PyPulse#6]
### Motivation
The objective is to modify or eliminate the window title bar.

### Description
Module name: Window (Created)
SubModule name: Bar (Not created)

The concept is to eliminate the standard window bar at your discretion, offering optional features to craft a customized alternative according to your preferences.

- Removing of the window bar
- Creating a custom window bar
- Some basic methods to pupulate with widgets the custom window bar.

### Tasks

- [x] Remove the original window bar (configuration in App.py settings)
- [ ] Create methods to create the new window bar
- [ ] Create basic interaction with the window bar all optional
   - [ ] Close
   - [ ] Minimize
   - [ ] Maximize
   - [ ] Title of the window
